SECRET_KEY = 'ADSSVSDG;Daf'

HOSTNAME="127.0.0.1"
PORT=3306
USERNAME = "root"
PASSWORD = "123456"
DATABASE = "project3"
DB_URI = f"mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4"
SQLALCHEMY_DATABASE_URI = DB_URI

WTF_CSRF_CHECK_DEFAULT = False

#邮箱配置
MAIL_SERVER = "smtp.qq.com"
MAIL_USE_SSL = True
MAIL_PORT = 465
MAIL_USERNAME = "2370403206@qq.com"
MAIL_PASSWORD = "qjnbozlwcpsieaeg"
MAIL_DEFAULT_SENDER = "2370403206@qq.com"